# The chats, messages and tool_calls tables were generated by ruby_llm 1.6.
# ruby_llm 2.0 owns a different schema, and nothing in this app read the old
# tables, so they are dropped and recreated by the 2.0 install generator.
class DropRubyLlm1xTables < ActiveRecord::Migration[8.1]
  def up
    drop_table :tool_calls, if_exists: true
    drop_table :messages, if_exists: true
    drop_table :chats, if_exists: true
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
